This will install the needed packages and start configuring the VPN client.

However before we start you will need to have received some information
from ZL1FLY. If you have not please e-mail him at robert (at) kneedrag (dot)
org.

Once you have received this run this script and answer the questions with 
the provided information. If in doubt please e-mail me.

Have you received this infomation e-mail from ZL1FLY
(Y/N)
